# Generated by Django 2.0.5 on 2018-08-11 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('address', models.TextField(verbose_name='Text')),
                ('script', models.TextField(verbose_name='Script')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=6)),
                ('date', models.DateField(verbose_name='Date')),
                ('url', models.URLField(max_length=100)),
                ('lecturer', models.TextField(max_length=2000)),
                ('place', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(verbose_name='event text')),
                ('date', models.DateField(verbose_name='date published')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('rid', models.PositiveIntegerField(blank=True, editable=False, unique=True, verbose_name='id')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='history')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('caption', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('nameLittle', models.TextField(max_length=20)),
                ('mission', models.TextField(verbose_name='institute mission')),
                ('link1Title', models.CharField(blank=True, max_length=50)),
                ('link1Link', models.URLField(blank=True)),
                ('link2Title', models.CharField(blank=True, max_length=50)),
                ('link2Link', models.URLField(blank=True)),
                ('link3Title', models.CharField(blank=True, max_length=50)),
                ('link3Link', models.URLField(blank=True)),
                ('link4Title', models.CharField(blank=True, max_length=50)),
                ('link4Link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagename', models.CharField(max_length=20, unique=True)),
                ('pagetext', models.TextField(verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='PhDProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='about program')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date published')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(verbose_name='position description')),
            ],
        ),
        migrations.CreateModel(
            name='PrInvestigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=35, verbose_name='rang')),
                ('firstname', models.CharField(max_length=35)),
                ('lastname', models.CharField(max_length=35)),
                ('nick', models.CharField(max_length=35, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('labpage', models.URLField(blank=True, max_length=50)),
                ('scholar', models.URLField(blank=True, max_length=50)),
                ('pubmed', models.URLField(blank=True, max_length=50)),
                ('photo', models.ImageField(upload_to='images')),
                ('profile', models.TextField(verbose_name='Pr Investigator profile')),
                ('labPhoto', models.ImageField(blank=True, null=True, upload_to='images')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='en.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('authors', models.CharField(max_length=500)),
                ('journal', models.CharField(max_length=100)),
                ('volume', models.CharField(max_length=15)),
                ('pages', models.CharField(max_length=20)),
                ('date', models.DateField(verbose_name='date published')),
                ('pubmed', models.CharField(blank=True, max_length=15)),
                ('prInvestigator', models.ManyToManyField(blank=True, to='en.PrInvestigator')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('little', models.TextField(max_length=2000)),
                ('text', models.TextField(verbose_name='about research')),
                ('prInvestigator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research', to='en.PrInvestigator')),
            ],
        ),
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=35)),
                ('firstname', models.CharField(max_length=35)),
                ('lastname', models.CharField(max_length=35)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('prInvestigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='en.PrInvestigator')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=35)),
                ('lastname', models.CharField(max_length=35)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('position', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='SummerSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='about summer school')),
                ('date', models.DateField(verbose_name='Year')),
            ],
        ),
    ]
