# Generated by Django 2.0.5 on 2018-08-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('en', '0004_auto_20180804_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='pubmed',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
