# Generated by Django 2.0.5 on 2018-06-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fazly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='about Fazly')),
            ],
        ),
    ]
