# Generated by Django 2.0.5 on 2018-06-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0002_fazly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Senate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='senate')),
            ],
        ),
    ]
