# Generated by Django 2.0.5 on 2018-06-29 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0003_senate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('authors', models.CharField(max_length=500)),
                ('journal', models.CharField(max_length=50)),
                ('volume', models.CharField(max_length=15)),
                ('pages', models.CharField(max_length=20)),
                ('date', models.DateField(verbose_name='date published')),
                ('pubmed', models.URLField(max_length=150)),
                ('prInvestigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ru.PrInvestigator')),
            ],
        ),
    ]
