# Generated by Django 2.0.5 on 2018-06-29 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0004_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='prInvestigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ru.PrInvestigator'),
        ),
    ]
