# Generated by Django 2.0.5 on 2018-06-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0005_auto_20180629_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='prInvestigator',
        ),
        migrations.AddField(
            model_name='publication',
            name='prInvestigator',
            field=models.ManyToManyField(blank=True, null=True, to='ru.PrInvestigator'),
        ),
    ]
