# Generated by Django 2.0.5 on 2018-06-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0007_auto_20180629_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='pages',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='publication',
            name='volume',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
