# Generated by Django 2.0.5 on 2018-06-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0008_auto_20180629_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='pages',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='publication',
            name='volume',
            field=models.CharField(max_length=15),
        ),
    ]
