# Generated by Django 2.0.5 on 2018-06-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0009_auto_20180629_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='prInvestigator',
            field=models.ManyToManyField(blank=True, to='ru.PrInvestigator'),
        ),
    ]
