# Generated by Django 2.0.5 on 2018-06-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0011_auto_20180629_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='pr',
            new_name='prInvestigator',
        ),
    ]
