# Generated by Django 2.0.5 on 2018-06-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0012_auto_20180629_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prinvestigator',
            name='publications',
        ),
        migrations.AddField(
            model_name='prinvestigator',
            name='pubmed',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='prinvestigator',
            name='scholar',
            field=models.URLField(blank=True, max_length=50),
        ),
    ]
