# Generated by Django 2.0.5 on 2018-06-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0013_auto_20180629_2142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
