# Generated by Django 2.0.5 on 2018-08-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0014_delete_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='script',
            field=models.TextField(verbose_name='Script'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
    ]
