# Generated by Django 2.0.5 on 2018-08-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0015_auto_20180804_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='MainDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField(verbose_name='date published')),
            ],
        ),
    ]
