# Generated by Django 2.0.5 on 2018-08-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0017_auto_20180804_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='laboratories')),
            ],
        ),
        migrations.RemoveField(
            model_name='research',
            name='little',
        ),
    ]
