# Generated by Django 2.0.5 on 2018-08-04 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0018_auto_20180804_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='little',
            field=models.TextField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
