# Generated by Django 2.0.5 on 2018-08-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0023_auto_20180811_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('prInvestigator', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='Laboratories',
        ),
    ]
